export const REQUEST_REGISTER_EMAIL = 'REGISTER_EMAIL';
export const RECEIVE_USER_ID = 'RECEIVE_USER_ID';
export const REQUEST_OPEN = 'REQUEST_OPEN';
export const REQUEST_CLOSE = 'REQUEST_CLOSE';
export const SEND_KEEP_ALIVE = 'SEND_KEEP_ALIVE';
