export const REQUEST_REGISTER_EMAIL = 'REQUEST_REGISTER_EMAIL';
export const REQUEST_REGISTER_EMAIL_ERROR = 'REQUEST_REGISTER_EMAIL_ERROR';
export const REQUEST_REGISTER_EMAIL_SUCCESS = 'REQUEST_REGISTER_EMAIL_SUCCESS';

export const REQUEST_OPEN = 'REQUEST_OPEN';
export const REQUEST_OPEN_ERROR = 'REQUEST_OPEN_ERROR';
export const REQUEST_OPEN_SUCCESS = 'REQUEST_OPEN_SUCCESS';

export const REQUEST_CLOSE = 'REQUEST_CLOSE';
export const REQUEST_CLOSE_ERROR = 'REQUEST_CLOSE_ERROR';
export const REQUEST_CLOSE_SUCCESS = 'REQUEST_CLOSE_SUCCESS';

export const SEND_KEEP_ALIVE = 'SEND_KEEP_ALIVE';
export const SEND_KEEP_ALIVE_ERROR = 'SEND_KEEP_ALIVE_ERROR';
export const SEND_KEEP_ALIVE_SUCCESS = 'SEND_KEEP_ALIVE_SUCCESS';
